name: Release
on:
  push:
    tags:
      - '*.*.*-kafka-*.*.*-*.*.*'
jobs:  
  docker_push:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get tag
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm/v7
          build-args: VERSION=${{ steps.get_tag.outputs.TAG }}
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/strimzi-kafka-operator-aws-msk-iam-auth:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/strimzi-kafka-operator-aws-msk-iam-auth:${{ steps.get_tag.outputs.TAG }}